name: ai_chatbot
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash:
  flutter_launcher_icons:
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/gemini_icon.png"
  android: true
  web: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/gemini_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/gemini_icon.png"
  adaptive_icon_foreground_inset: 30
  web:
    generate: true
    image_path: "assets/gemini_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/gemini_icon.png
    - assets/gemini_splash.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
